from app.interfaces.enum_interface import EnumInterface

class DirectorateCode(EnumInterface):
    FB = "FutureBrand"
    ASG = "Unidade ASG"
    BB_ASSET = "BB Asset"
    BB_CONSORCIOS = "BB Consórcios"
    BB_SEGUROS = "BB Seguros"
    CCBB = "CCBB – Centro Cultural do Banco do Brasil"
    CIB = "CIB – Corporate Bank and Investment Bank"
    COGER = "COGER – Diretoria Contadoria"
    CRM = "CRM – Unidade CRM e Indução Digital de Clientes"
    DEMPE = "DEMPE – Diretoria Empreendedorismo Micro e Pequenas Empresas"
    DICOI = "DICOI – Diretoria de Controles Internos"
    DICOR = "DICOR – Diretoria Corporate Bank"
    DICRE = "DICRE – Diretoria de Crédito"
    DIEMP = "DIEMP – Diretoria Soluções em Empréstimos e Financiamento"
    DIFIN = "DIFIN – Diretoria Finanças"
    DIGOV = "DIGOV – Diretoria Negócios Governo"
    DIJUR = "DIJUR – Diretoria Jurídica"
    DIMAC_GERAL = "DIMAC – Diretoria Marketing e Comunicação"
    DIMEP = "DIMEP – Diretoria Soluções em Meios de Pagamentos e Serviços"
    DINED = "DINED – Diretoria de Negócios Digitais"
    DIOPE = "DIOPE – Diretoria Operações"
    DIPES = "DIPES – Diretoria Gestão da Cultura e de Pessoas"
    DIRAG = "DIRAG – Diretoria Agronegócios e Agricultura Familiar"
    DIRCO = "DIRCO – Diretoria de Controladoria"
    DIREC = "DIREC – Diretoria de Clientes Varejo PF"
    DIREO = "DIREO – Diretoria Estratégia e Organização"
    DIRIS = "DIRIS – Diretoria Gestão de Riscos"
    DISEC = "DISEC – Diretoria de Suprimentos, Infraestrutura e Patrimônio"
    DITEC = "DITEC – Diretoria de Tecnologia"
    DIVAR = "DIVAR – Diretoria Comercial Varejo"
    OUVIDORIA = "Ouvidoria"
    TESOURARIA_GLOBAL = "Tesouraria Global"
    UAC = "UAC – Unidade Atendimento e Canais Físicos e Digitais"
    UAN = "UAN – Unidade Inteligência Artificial e Analítica"
    UCI = "UCI – Unidade Captação e Investimentos"
    UCR = "UCR – Unidade Cobrança e Reestruturação de Ativos Operacionais"
    UEG = "UEG – Unidade Estratégia Governo"
    UGR = "UGR – Unidade Governança Corporativa e Relações Institucionais"
    UNI = "UNI – Unidade Negócios Internacionais"
    UNJ = "UNJ – Unidade Empréstimos e Financiamentos PJ"
    UPB = "UPB – Unidade Private Bank"
    UPE = "UPE – Unidade Participações e Parcerias Estratégicas"
    URI = "URI – Unidade Relacionamento com Investidores"
    USD = "USD – Unidade Segurança Digital e da Informação"
    USI = "USI – Unidade Segurança Institucional"
    RESTRITO = "Pautas Políticas Sensíveis"
    DIMAC_PRIORITARIO = "DIMAC Prioritário – Equipe Risco de Reputação"

    @classmethod
    def list_excluding(cls):
        exclusions = {cls.FB, cls.DIMAC_PRIORITARIO}
        return [member for member in cls if member not in exclusions]
